name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master
      - 12-deploy-actions
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v2
        with:
          java-version: '17.x'
          distribution: 'temurin'
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18' # Ensure compatibility with Firebase CLI
      
      - run: npm install -g firebase-tools
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Web
        run: flutter build web
      
      - name: Setup Firebase Service Account
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase-service-account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-service-account.json" >> $GITHUB_ENV
      
      - name: Deploy to Firebase
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-service-account.json
          firebase deploy --only hosting
        