name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master
      - 12-deploy-actions
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a version compatible with Firebase CLI
      - run: npm install -g firebase-tools
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Web
        run: flutter build web
      - name: Setup Firebase Service Account
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}      
      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        
